// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

namespace protobufnet
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Person : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private int? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"age")]
        public uint Age
        {
            get => __pbn__Age.GetValueOrDefault();
            set => __pbn__Age = value;
        }
        public bool ShouldSerializeAge() => __pbn__Age != null;
        public void ResetAge() => __pbn__Age = null;
        private uint? __pbn__Age;

        [global::ProtoBuf.ProtoMember(4, Name = @"book")]
        public AddressBook Book { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"nums", IsPacked = true)]
        public int[] Nums { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"mons", IsPacked = true)]
        public float[] Mons { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"years", IsPacked = true)]
        public double[] Years { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddressBook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private int? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Address
        {
            get => __pbn__Address ?? "";
            set => __pbn__Address = value;
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private string __pbn__Address;

        [global::ProtoBuf.ProtoMember(3, Name = @"phones")]
        public global::System.Collections.Generic.List<AddressPhone> Phones { get; } = new global::System.Collections.Generic.List<AddressPhone>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddressPhone : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private int? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"phone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Phone
        {
            get => __pbn__Phone ?? "";
            set => __pbn__Phone = value;
        }
        public bool ShouldSerializePhone() => __pbn__Phone != null;
        public void ResetPhone() => __pbn__Phone = null;
        private string __pbn__Phone;

        [global::ProtoBuf.ProtoMember(3, Name = @"email")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Email
        {
            get => __pbn__Email ?? "";
            set => __pbn__Email = value;
        }
        public bool ShouldSerializeEmail() => __pbn__Email != null;
        public void ResetEmail() => __pbn__Email = null;
        private string __pbn__Email;

        [global::ProtoBuf.ProtoMember(4, Name = @"serial")]
        public double Serial
        {
            get => __pbn__Serial.GetValueOrDefault();
            set => __pbn__Serial = value;
        }
        public bool ShouldSerializeSerial() => __pbn__Serial != null;
        public void ResetSerial() => __pbn__Serial = null;
        private double? __pbn__Serial;

        [global::ProtoBuf.ProtoMember(5, Name = @"cost")]
        public float Cost
        {
            get => __pbn__Cost.GetValueOrDefault();
            set => __pbn__Cost = value;
        }
        public bool ShouldSerializeCost() => __pbn__Cost != null;
        public void ResetCost() => __pbn__Cost = null;
        private float? __pbn__Cost;

    }

}
